image: reg.tre-pa.jus.br/library/maven:3.6-jdk-8

default:
  tags:
    - k8s-runner

variables:
  MAVEN_CLI_OPTS: "-Dmaven.repo.local=/.m2/repository -s .m2/settings.xml --batch-mode -Djkube.resourceDir=springboot-angular-dxdatagrid-lab-backend/src/main/jkube"
  DOCKER_REGISTRY: "reg.tre-pa.jus.br"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2

stages:
  - build-jar
  - build-image
  - deploy-k8s-dev
  - deploy-k8s-hmg
  - deploy-k8s-prod

build-jar:
  stage: build-jar
  before_script:
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    - nvm install 10
    - echo "APPVERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -Dmaven.repo.local=/.m2/repository -s .m2/settings.xml)-${CI_COMMIT_SHORT_SHA}" > ./version.env
  script:
    - mvn package -Dskip.integration.tests=true -Dskip.unit.tests=true $MAVEN_CLI_OPTS
    - (cd ./springboot-angular-dxdatagrid-lab-backend/ && mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar))
  artifacts:
    reports:
      dotenv: ./version.env
    expire_in: 1 day
    paths:
      - ./springboot-angular-dxdatagrid-lab-backend/target/
      - ./version.env
  only:
    - main

build-image:
  stage: build-image
  services:
    - name: reg.tre-pa.jus.br/library/docker:20.10.7-dind
      command: [ "--insecure-registry", "reg.tre-pa.jus.br" ]
  script:
    - sleep 15
    - mvn docker:build docker:push $MAVEN_CLI_OPTS 
  only:
    - main

deploy-k8s-dev:
  stage: deploy-k8s-dev
  script: 
    - mvn k8s:resource -N $MAVEN_CLI_OPTS
    - mvn k8s:apply -N -Djkube.namespace=sds-dev $MAVEN_CLI_OPTS
  environment:
    name: dev
    url: https://dev-k8s.tre-pa.jus.br/$CI_PROJECT_NAME
  only:
    - main

deploy-k8s-hmg:
  stage: deploy-k8s-hmg
  before_script:
    - export APPVERSION=$(curl -s --insecure --location --header "PRIVATE-TOKEN:${GITLAB_CICD_TOKEN}" "https://git.tre-pa.jus.br/api/v4/projects/${CI_PROJECT_ID}/jobs/artifacts/master/raw/version.env?job=build-jar" | sed -n 's/.*=//p')
  script: 
    - mvn k8s:resource $MAVEN_CLI_OPTS
    - mvn k8s:apply -N -Djkube.namespace=sds-hmg $MAVEN_CLI_OPTS
  environment:
    name: hmg
    url: https://hmg-k8s.tre-pa.jus.br/$CI_PROJECT_NAME
  only:
    - hmg

deploy-k8s-prod:
  stage: deploy-k8s-prod
  before_script:
    - export APPVERSION=$(curl -s --insecure --location --header "PRIVATE-TOKEN:${GITLAB_CICD_TOKEN}" "https://git.tre-pa.jus.br/api/v4/projects/${CI_PROJECT_ID}/jobs/artifacts/master/raw/version.env?job=build-jar" | sed -n 's/.*=//p')
  script:
    - mvn k8s:resource $MAVEN_CLI_OPTS
    - mvn k8s:apply -N -Djkube.namespace=sds-prod $MAVEN_CLI_OPTS
  environment:
    name: prod
    url: https://prod-k8s.tre-pa.jus.br/$CI_PROJECT_NAME
  only:
    - prod
