spring:
  datasource:
    url: ENC(3LyeNajOvnuka2YyDqet1+vhIjQhkwxFDkA3/EcLiSqjuC+IyjMXiTpYnKE1/UlKGZwrXB+kX7YQXZfGkeML11nJOFV3SGiNHyI43xCYQoiybo5UI/PTffm9uJTqLZerEnG2dmNtpWz2kqN6evNTjw==)
    driver-class-name: ENC(zzlmjrhTnpGt1atw93PGck9rkEyRG3xEMtpNCGC0SIft+zXA5qBUUws2RVA/wkwdThr6tFEP8GXhWaceLMoSRw==)
    username: ENC(tAB6hqRa+U4lcanKhonh4mBpXv6APu3sARpfEfC6Qy+eeiDBFPkj8OTbxsxlwCIR)
    password: ENC(JeesEUScspyRMMN+YXpydhMXdndcpnxEX7dwkB7Bocj7/oC3pMdb8VC6X3cPLA6c)
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    mapper:
      default-view-inclusion: true
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
info:
  app:
    name: @project.name@
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    web:
      exposure:
        include: "health,info,prometheus,auditevents"
endpoints:
  auditevents: "*"
flyway:
  oracle:
    sqlplus: true
